version: "3.9"

services:
  influxdb:
    image: influxdb:1.8.10 # influxdb latest 1.X version.
    container_name: influxdb
    restart: always # ensures container will be started after rebooting host system.
    ports:
      - "8086:8086" # expose for localhost.
    volumes:
      - $HOME/docker/influxdb/data:/var/lib/influxdb # for data persistence.
      - $HOME/docker/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro # influxdb configuration file.
      - $HOME/docker/influxdb/init:/docker-entrypoint-initdb.d # executes on first start of container, bootstraps influxdb.
    environment:
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER} # sourced from .env.
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD} # sourced from .env.

  telegraf:
    image: sebd/telegraf-rpi:latest # telegraf container extended by the rpi packages, used for the vcgenmd utility.
    restart: always 
    container_name: telegraf
    volumes:
      - $HOME/docker/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro # config for telegraf instance, mounted in the container as read only.
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro
      - /:/rootfs:ro
    devices:  
      - /dev/vchiq:/dev/vchiq # mapping interface that run betweens kernel and peripherals for gpu temps.
    environment:
       HOST_ETC: /rootfs/etc
       HOST_PROC: /rootfs/proc
       HOST_SYS: /rootfs/sys
       HOST_HOSTNAME: # used to pass the the docker host hostname.

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always 
    user: "1000" 
    ports:
     - "3030:3000" # expose for localhost - test with 3030.
    volumes: 
     - $HOME/docker/grafana/data:/var/lib/grafana # data path for data persistence.
     - $HOME/docker/grafana/grafana.ini:/etc/grafana/grafana.ini # config for grafana instance.
     - $HOME/docker/grafana/provisioning:/etc/grafana/provisioning # for provisioning scripts, storing dashboards and datasources.
    environment: 
     - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER} # sourced from .env.
     - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD} # sourced from .env.
