
---
- name: Check if Docker is already installed.
  command: which docker
  failed_when: false
  changed_when: false
  register: which_docker

- name: Download Docker install convenience script.
  get_url:
    url: https://get.docker.com/
    dest: /tmp/get-docker.sh
    mode: 0775
  when: which_docker.rc == 1 # rc = return code, 1 is general error.

- name: Run Docker install convenience script.
  command: /tmp/get-docker.sh
  environment:
    CHANNEL: stable
  when: which_docker.rc == 1 # rc = return code, 1 is general error.

- name: Ensure Docker is started and runs upon boot.
  service:
    name: docker
    state: started
    enabled: yes

- name: Install Docker Compose with pip3.
  pip:
    name: docker-compose
    state: present
    executable: pip3

- name: Ensure pi user is added to the Docker group.
  user:
    name: pi
    groups: docker
    append: yes
  notify: reset_connection # group membership is evaluated at login time only.




